- op: replace
  path: /spec/template/spec/hostAliases/0/ip
  value: "TRAEFIK_IP"
- op: replace
  path: /spec/template/spec/hostAliases/0/hostnames
  value:
    - "api.TENANT_DOMAIN"
    - "minio-console.TENANT_DOMAIN"
    - "minio.TENANT_DOMAIN"
    - "TENANT_DOMAIN"
