apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront
  spec:
    template:
      spec:
        initContainers:
          - name: wait-for-medusa
            env:
              - name: SECRET_NAME
                value: storefront-key
        containers:
          - name: storefront
            envFrom:
              - secretRef:
                  name: storefront-key
