export const EXCLUDED_ROUTES = ["/admin/auth", "/admin/rbac/v2/check", "/admin/invite"];
export const DEFAULT_CATEGORIES = [
  { name: "Products", description: "Manage products and inventory" },
  { name: "Orders", description: "Manage orders and fulfillment" },
  { name: "Customers", description: "Manage customers" },
  { name: "Users", description: "Manage admin users" },
  { name: "Invites", description: "Manage admin invites" },
  { name: "Settings", description: "Manage store settings" },
  { name: "Price Lists", description: "Manage price lists" },
  { name: "Promotions", description: "Manage promotions and discounts" },
  { name: "Gift Cards", description: "Manage gift cards" },
];

export const PREDEFINED_PERMISSIONS = [
  { kind: "read", target: "/admin/products", category: "Products" },
  { kind: "write", target: "/admin/products", category: "Products" },
  { kind: "delete", target: "/admin/products", category: "Products" },
  { kind: "read", target: "/admin/orders", category: "Orders" },
  { kind: "write", target: "/admin/orders", category: "Orders" },
  { kind: "delete", target: "/admin/orders", category: "Orders" },
  { kind: "read", target: "/admin/customers", category: "Customers" },
  { kind: "write", target: "/admin/customers", category: "Customers" },
  { kind: "delete", target: "/admin/customers", category: "Customers" },
  { kind: "read", target: "/admin/users", category: "Users" },
  { kind: "write", target: "/admin/users", category: "Users" },
  { kind: "delete", target: "/admin/users", category: "Users" },
  { kind: "read", target: "/admin/invite", category: "Invites" },
  { kind: "write", target: "/admin/invite", category: "Invites" },
  { kind: "read", target: "/admin/store", category: "Settings" },
  { kind: "write", target: "/admin/store", category: "Settings" },
  { kind: "read", target: "/admin/price-lists", category: "Price Lists" },
  { kind: "write", target: "/admin/price-lists", category: "Price Lists" },
  { kind: "delete", target: "/admin/price-lists", category: "Price Lists" },
  { kind: "read", target: "/admin/promotions", category: "Promotions" },
  { kind: "write", target: "/admin/promotions", category: "Promotions" },
  { kind: "delete", target: "/admin/promotions", category: "Promotions" },
  { kind: "read", target: "/admin/gift-cards", category: "Gift Cards" },
  { kind: "write", target: "/admin/gift-cards", category: "Gift Cards" },
  { kind: "delete", target: "/admin/gift-cards", category: "Gift Cards" },
];
