apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smap-store

resources:
  - ../../base/namespace.yaml
  - ../../base/postgres.yaml
  - ../../base/redis.yaml
  - ../../base/minio.yaml
  - ../../base/minio-init.yaml
  - ../../base/medusa.yaml
  - ../../base/medusa-init.yaml
  - ../../base/storefront.yaml
  - ../../base/ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: smap-store
      environment: staging
    includeSelectors: true

images:
  - name: smap-store-medusa
    newTag: "latest"
  - name: smap-store-storefront
    newTag: "latest"
