services:
  # Traefik configuration for development
  traefik:
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.transport.respondingTimeouts.readTimeout=0"
      - "--entrypoints.web.transport.respondingTimeouts.writeTimeout=0"
      - "--entrypoints.web.transport.respondingTimeouts.idleTimeout=180s"
      - "--log.level=DEBUG"
      - "--accesslog=true"
