name: ${PROJECT_NAME:-smap-store}

# include:
#   - docker-compose.infra.yml
#   - docker-compose.build.yml
#   - docker-compose.ingress.yml

volumes:
  postgres_data:
  minio_data:

networks:
  medusa_network:
    driver: bridge
