apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smap-store-development

resources:
  - ../../base

images:
  - name: medusa
    newName: localhost:5000/smap-store-medusa
    newTag: latest
  - name: storefront
    newName: localhost:5000/smap-store-storefront
    newTag: latest

patches:
  - path: patches/replicas.yaml
    target:
      kind: Deployment
      name: medusa
  - path: patches/replicas.yaml
    target:
      kind: Deployment
      name: storefront
