apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smap-store-TENANT_NAME

resources:
  - ../../base

images:
  - name: medusa
    newName: REGISTRY/smap-store-medusa
    newTag: IMAGE_TAG
  - name: storefront
    newName: REGISTRY/smap-store-storefront
    newTag: IMAGE_TAG

patches:
  - path: patches/hostAliases.yaml
    target:
      kind: Deployment
      name: storefront
  - path: patches/replicas.yaml
    target:
      kind: Deployment
      name: medusa
