export const SAMPLE_DATA = {
    companyName: "Sample Company",
    companyAddress: "123 Business Street\nNew York, NY 10001",
    companyPhone: "+1 (555) 123-4567",
    companyEmail: "contact@samplecompany.com",
    companyLogo: null as string | null,
    invoiceNumber: "0001",
    invoiceDate: new Date().toLocaleDateString(),
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toLocaleDateString(),
    customerName: "John Doe",
    customerAddress: "456 Customer Ave",
    customerCity: "Los Angeles",
    customerCountry: "US",
    customerPhone: "+1 (555) 987-6543",
    customerEmail: "john.doe@example.com",
    lineItems: [
        {
            description: "Product Item 1",
            quantity: 2,
            unitPrice: "50.00",
            total: "100.00",
            sku: "SKU-001",
        },
        {
            description: "Product Item 2",
            quantity: 1,
            unitPrice: "75.00",
            total: "75.00",
            sku: "SKU-002",
        },
        {
            description: "Product Item 3",
            quantity: 3,
            unitPrice: "25.00",
            total: "75.00",
            sku: "SKU-003",
        },
    ],
    subtotal: "250.00",
    taxRate: "19",
    taxAmount: "47.50",
    shipping: "15.00",
    total: "312.50",
    currency: "USD",
    notes: "Thank you for your business!",
    dir: "ltr",
    isRtl: false,
    t: {
        invoice: "Invoice",
        invoiceNumber: "Invoice #",
        date: "Date",
        dueDate: "Due Date",
        billTo: "Bill To",
        item: "Item",
        description: "Description",
        quantity: "Qty",
        unitPrice: "Unit Price",
        total: "Total",
        subtotal: "Subtotal",
        tax: "Tax",
        shipping: "Shipping",
        grandTotal: "Grand Total",
        notes: "Notes",
    },
};