apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smap-store-ingress
  namespace: smap-store
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: traefik
  rules:
    - host: "api.localhost"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: medusa
                port:
                  number: 9000
    - host: "shop.localhost"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: storefront
                port:
                  number: 80
    - host: "minio.localhost"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console-ingress
  namespace: smap-store
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: traefik
  rules:
    - host: "minio-console.localhost"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9001
