apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smap-store

resources:
  - 00-namespace.yaml
  - postgres.yaml
  - redis.yaml
  - minio.yaml
  - minio-init.yaml
  - medusa-init.yaml
  - medusa.yaml
  - storefront.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: smap-store
